// /ind-fitness — value-led rewrite (AR, Egyptian, primary). See docs/website/BUILD-BRIEF.md.
const html = `<div class="pg-ind-fitness">
<section class="phero pind"><div class="container phero-in">
  <div>
    <div class="crumb"><a href="/use-cases">الحلول</a> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg> <span>الجيمات ومراكز اللياقة</span></div>
    <h1>الحصص التجريبية بتتحجز، أسئلة الاشتراكات بتتجاوب، والاستقبال فاضي للأعضاء.</h1>
    <p class="lead">أسئلة الكلاسات والباقات بتيجي على <bdi>WhatsApp</bdi> في أي وقت. موظفك الذكي المتدرّب على جيمك بيحجز الحصة التجريبية، ويجاوب عن الاشتراكات، ويتابع لحد ما الاشتراك يتدفع، فمحدش بيستنى وفريقك يفضل جوه الجيم.</p>
    <div class="heroc-cta"><a href="/contact" class="btn btn-primary btn-lg">احجز جلسة تخطيط</a><a href="https://app.genudo.ai/auth/register" class="btn btn-ondark btn-lg">ابدأ مجانًا</a></div>
    <div class="pchips"><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>حجز الحصص التجريبية</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></svg>أسئلة الاشتراكات</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg>تذكير ومتابعة</span></div>
  </div>
  <div class="phero-media"><div class="pg-hero-ph"><div class="mk mk-phone" dir="rtl" lang="ar" role="img" aria-label="محادثة WhatsApp: زائر بيحجز حصة تجريبية">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">ك</span><div class="mk-phone__who"><b>كريم سعيد</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>الموظف الذكي بيتولّى المحادثة دي</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>تدخّل بشري</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">اليوم</span>
      <div class="mk-msg mk-msg--in">أهلًا! عايز أجرّب كلاس كروس فيت قبل ما أشترك. ينفع؟<span class="mk-msg__meta"><bdi>6:20</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>أهلًا يا كريم! أكيد. عندي بكرة <bdi>7</bdi> أو <bdi>8:30</bdi> بالليل، أنهي يناسبك؟<span class="mk-msg__meta"><bdi>6:20</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">الساعة <bdi>7</bdi> كويس<span class="mk-msg__meta"><bdi>6:21</bdi> م</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">الحصة التجريبية اتحجزت</div><div class="mk-meeting__when">الأربع، <bdi>7</bdi> م</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>جيم برايم فيت</span><span><i class="mk-ic mk-ic--check"></i>حصة تجريبية</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">الموظف الذكي بيتولّى المحادثة دي. اضغط «تدخّل بشري» عشان ترد بنفسك.</div>
  </div>
</div></div></div>
</div></section>

<section class="s white-bg"><div class="container">
  <div class="s-head"><span class="eyebrow">اللي بيعطّلك</span><h2>اللياقة حاجة شخصية، والناس عايزة ردّ سريع.</h2><p class="lead">لما حد بيختار جيم أو بيحجز كلاس، أي رد متأخر بيضيّع اشتراك.</p></div>
  <div class="feat-grid" style="margin-top:34px"><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></div><h4>الأسئلة بتعطّل الحجز</h4><p>الناس بتسيب لما ما تقدرش تتأكد بسرعة من تفاصيل الكلاس أو السعر أو المواعيد المتاحة.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg></div><h4>الاستقبال بيجاوب نفس السؤال طول اليوم</h4><p>الكباتن والاستقبال بيضيّعوا ساعات على نفس أسئلة الجدول والسياسات والاشتراكات.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg></div><h4>الأعضاء الجداد بيبعدوا</h4><p>العضو الجديد اللي محدش بيرد على أسئلته عن الكلاسات والمدربين بيبطّل ييجي في أسابيع، والاشتراك بيروح معاه.</p></div></div>
</div></section>

<section class="s tint-bg" id="fit"><div class="container">
  <div class="s-head"><span class="eyebrow">فريقك الذكي</span><h2>فريقك الذكي في مراكز اللياقة</h2><p class="lead">عارف بيبيع، وعدنان بيهتم بالعملاء، وروز بتساعد فريقك يحسّن محادثاته على واتساب. وظّف واحد منهم أو التلاتة. كل مثال هنا مثال افتراضي، وكل رقم معاه رابط مصدره.</p></div>
  <div class="pg-team"><article class="pg-tm pg-tm--aaref"><div class="pg-tm__head"><img src="/media/img/aaref.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>عارف</h3><span class="pg-tm__role">موظف مبيعات ذكي</span></div><a class="pg-go" href="/sol-sales-agent">اتعرف على عارف <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">استفسار السعر يتحول لاشتراك</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>استفسار السعر بيترد عليه تاني يوم، واللي جرّب أو زار المركز محدش بيتابع معاه.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>أول أسبوع في يناير في المعادي: عشرات الاستفسارات عن الأسعار كل ساعة. عميلة حجزت حصة تجريبية، من غير تذكير ولا متابعة.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>استفسارات الموقع اترد عليها خلال 24 ساعة في 61% بس من الحالات، و35% بس من المهتمين اتواصلوا معاهم في التوقيت اللي المركز نفسه محدده (<a href="https://www.healthclubmanagement.co.uk/health-club-management-features/Only-60-of-in-person-gym-membership-enquiries-are-asked-for-contact-details/30424" target="_blank" rel="noopener"><bdi>UK mystery shop, 500+ clubs</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بيعمله عارف</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيرد على الباقات والكلاسات والعروض 24 ساعة</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحجز الحصة التجريبية أو يسجّل العضو</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيتابع بعد الحصة التجريبية لحد إتمام الاشتراك</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>من حصة تجريبية لاشتراك</span><span>أعضاء جداد في الشهر</span><span>سرعة الرد</span></div></div></div></article>
<article class="pg-tm pg-tm--adnan"><div class="pg-tm__head"><img src="/media/img/adnan.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>عدنان</h3><span class="pg-tm__role">موظف خدمة ونجاح عملاء ذكي</span></div><a class="pg-go" href="/sol-customer-service">اتعرف على عدنان <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">أعضاء مستمرين</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>الأعضاء الجداد بيوقفوا بدري، وأسئلة الكلاسات والمدربين بتتراكم، ونفس أسئلة المواعيد طول اليوم.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>عضوة جديدة بتسأل الساعة 10 بالليل عن الكلاس المناسب للمبتدئين وإزاي تحجزه. محدش بيرد، وفي الأسبوع التالت بتبطّل تيجي.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>63% من الأعضاء الجداد بيوقفوا قبل الشهر التالت، وأقل من 4% بيكمّلوا سنة (<a href="https://pubmed.ncbi.nlm.nih.gov/26874647/" target="_blank" rel="noopener"><bdi>Sperandei et al. 2016</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بيعمله عدنان</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيجاوب على المواعيد والكلاسات وأسئلة المدربين 24 ساعة</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحجز ويغيّر مواعيد الكلاسات حسب قواعدك، ويبلّغ الاستقبال</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيتابع مع الأعضاء الجداد في أول أسابيعهم</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>الاستمرار بعد 3 شهور</span><span>حجوزات الكلاسات</span><span>رسائل الاستقبال</span></div></div></div></article>
<article class="pg-tm pg-tm--roz"><div class="pg-tm__head"><img src="/media/img/roz-v2.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>روز</h3><span class="pg-tm__role">موظفة مراقبة جودة ذكية</span></div><a class="pg-go" href="/sol-operations">اتعرف على روز <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">استقبال بيحقق مبيعات</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>اللي جرّبوا حصة تجريبية محدش بيتواصل معاهم، والأسعار بتتقال بأشكال مختلفة، وأسئلة الأعضاء بتفضل أيام من غير رد.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>مركز لياقة في الشيخ زايد بيطلق عرض صيفي: 3 أسعار مختلفة على واتساب، واللي جرّبوا محدش اتواصل معاهم، وسؤال عضو من غير رد لمدة أسبوع.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>35% بس من المهتمين اتواصلوا معاهم في التوقيت اللي المركز محدده، واتعرض عليهم الاشتراك في 56% بس من الحالات (<a href="https://www.healthclubmanagement.co.uk/health-club-management-features/Only-60-of-in-person-gym-membership-enquiries-are-asked-for-contact-details/30424" target="_blank" rel="noopener"><bdi>UK mystery shop, 500+ clubs</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بتعمله روز</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بتوضّح في التقارير اللي جرّبوا والمهتمين اللي من غير متابعة</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بتوضّح أسئلة الأعضاء اللي من غير رد</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>ملاحظات تطوير تساعد الاستقبال يعرض الاشتراك ويقفله</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>المتابعة خلال 48 ساعة</span><span>من تجربة لاشتراك</span><span>أسئلة اتجاوبت</span></div></div><p class="pg-tm__note pg-tm__wide">طريقة شغلها: بتسألها في Claude أو ChatGPT، وبتبعتلك تقارير على جدول، وبتغذّي الـ dashboards بتاعتك. مسح كود QR واحد لكل رقم واتساب للشركة بيربط محادثاتك وجروباتك، وبتبدأ في نفس اليوم.</p></div></article>
</div>
</div></section>

<section class="s white-bg" id="conversation"><div class="container">
  <div class="s-head"><span class="eyebrow">محادثات حقيقية</span><h2>حصة تجريبية اتحجزت وعضوة جديدة اتساعدت، كله على <bdi>WhatsApp</bdi>.</h2><p class="lead">محادثتين مبقاش لازم الاستقبال يرد عليهم بإيده. مثال افتراضي، والخطوات حقيقية.</p></div>
  <div class="pg-duo pg-duo--2"><div class="pg-ph"><div class="mk mk-phone" dir="rtl" lang="ar" role="img" aria-label="محادثة WhatsApp: زائر بيحجز حصة تجريبية">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">ك</span><div class="mk-phone__who"><b>كريم سعيد</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>الموظف الذكي بيتولّى المحادثة دي</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>تدخّل بشري</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">اليوم</span>
      <div class="mk-msg mk-msg--in">أهلًا! عايز أجرّب كلاس كروس فيت قبل ما أشترك. ينفع؟<span class="mk-msg__meta"><bdi>6:20</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>أهلًا يا كريم! أكيد. عندي بكرة <bdi>7</bdi> أو <bdi>8:30</bdi> بالليل، أنهي يناسبك؟<span class="mk-msg__meta"><bdi>6:20</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">الساعة <bdi>7</bdi> كويس<span class="mk-msg__meta"><bdi>6:21</bdi> م</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">الحصة التجريبية اتحجزت</div><div class="mk-meeting__when">الأربع، <bdi>7</bdi> م</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>جيم برايم فيت</span><span><i class="mk-ic mk-ic--check"></i>حصة تجريبية</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">الموظف الذكي بيتولّى المحادثة دي. اضغط «تدخّل بشري» عشان ترد بنفسك.</div>
  </div>
</div></div><div class="pg-ph"><div class="mk mk-phone" role="img" aria-label="محادثة WhatsApp: عضوة جديدة بتسأل عن كلاس للمبتدئين وبيتحجزلها">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">م</span><div class="mk-phone__who"><b>منى عادل</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>الموظف الذكي بيتولّى المحادثة دي</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>تدخّل بشري</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">اليوم</span>
      <div class="mk-msg mk-msg--in">أهلًا! أنهي كلاس يناسب مبتدئة؟ وأحجزه إزاي؟<span class="mk-msg__meta">10:02 م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عدنان · موظف ذكي</span>أهلًا يا منى! للمبتدئين أنسبلك كلاس الأساسيات، التلات والخميس الساعة <bdi>7</bdi> بالليل. أحجزلك الخميس ده؟<span class="mk-msg__meta">10:02 م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">أيوه ياريت<span class="mk-msg__meta">10:03 م</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">الكلاس اتحجز</div><div class="mk-meeting__when">الخميس، <bdi>7</bdi> م</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>كلاس الأساسيات</span><span><i class="mk-ic mk-ic--check"></i>الاستقبال اتبلّغ</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">الموظف الذكي بيتولّى المحادثة دي. اضغط «تدخّل بشري» عشان ترد بنفسك.</div>
  </div>
</div></div></div>
  <ul class="plist pg-proof"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحجز الحصة التجريبية على جدولك مباشرة</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيجاوب من باقاتك وسياساتك إنت، مش من التخمين</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحوّل أي حاجة حساسة للاستقبال والتفاصيل متجمّعة</li></ul>
</div></section>

<section class="s tint-bg" id="followup"><div class="container">
  <div class="prow">
    <div class="prow-copy"><span class="eyebrow">المتابعة</span><h3>اللي جرّب ومشتركش لسه بيسمع منك.</h3><p>بعد الحصة التجريبية، عارف بيتابع على جدول إنت بتحدده، بأسلوب جيمك، وبيوقف لما الشخص يرد أو التسلسل يخلص. فريقك بيدخل لما حد يبقى جاهز يشترك.</p></div>
    <div class="prow-media pg-fu"><div class="mk mk-card" dir="rtl" lang="ar" role="img" aria-label="تسلسل المتابعات بعد الحصة التجريبية">
  <div class="mk-card__head"><div class="mk-card__title"><i class="mk-ic mk-ic--repeat"></i>المتابعات · حصة تجريبية</div><span class="mk-chip mk-chip--green"><i class="mk-dot"></i>نشطة</span></div>
  <ol class="mk-timeline">
    <li class="mk-step is-sent"><div class="mk-step__head"><b>المتابعة 1</b><span class="mk-step__wait">بعد 3 ساعات</span><span class="mk-status mk-status--sent">مُرسلة</span></div><p class="mk-step__msg">أهلًا يا كريم، عامل إيه بعد أول كلاس؟ تحب أعرّفك على الباقات؟</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>المتابعة 2</b><span class="mk-step__wait">بعد يوم واحد</span><span class="mk-status mk-status--scheduled">مجدولة</span></div><p class="mk-step__msg">تحب أحجزلك كلاس تاني الأسبوع ده؟</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>المتابعة 3</b><span class="mk-step__wait">بعد 3 أيام</span><span class="mk-status mk-status--scheduled">مجدولة</span></div><p class="mk-step__msg">آخر تذكير: أسيبلك مكان الأسبوع ده؟</p></li>
    <li class="mk-step mk-step--end"><div class="mk-step__head"><i class="mk-ic mk-ic--arrow"></i>لا رد بعد انتهاء التسلسل: النقل إلى <span class="mk-stage mk-stage--red mk-stage--sm">ضائعة</span></div></li>
  </ol>
</div></div>
  </div>
</div></section>

<section class="s white-bg" id="how"><div class="container">
  <div class="s-head"><span class="eyebrow">بيشتغل إزاي</span><h2>إزاي بتوظّف فريقك الذكي</h2></div>
  <ol class="pg-steps"><li class="pg-step"><span class="pg-n">1</span><div><h4>خطّطوا مع بعض</h4><p>في جلسة التخطيط بنسمعك وبنفهم شغلك النهارده، ونخطّط معاك الموظف هيعمل إيه واللي يفضل عند فريقك. ومدة التنفيذ بنتفق عليها في الجلسة دي.</p></div></li><li class="pg-step"><span class="pg-n">2</span><div><h4>بنبني ونطلق</h4><p>متخصص الـ automation بيبني موظفك من معلوماتك إنت، وبعدين بيشتغل على الـ WhatsApp بتاعك.</p></div></li><li class="pg-step"><span class="pg-n">3</span><div><h4>بنحسّن معاك</h4><p>الـ account manager بيراجع النتايج معاك وبيفضل يظبط. وفريقك بيشوف كل المحادثات في الـ inbox واحد ويتدخّل بضغطة.</p></div></li></ol>
  <p class="pg-control">إنت اللي ماسك الدفة. تدخّل في أي محادثة بضغطة من موبايلك، وارجّعها للموظف لما تخلص. روز مش محتاجة تنفيذ: سجّل دخول، وامسح كود QR واحد لكل رقم واتساب للشركة، وبتبدأ في نفس اليوم.</p>
</div></section>

<section class="s tint-bg"><div class="container">
  <div class="s-head center"><span class="eyebrow">أسئلة</span><h2>حاجات تحب تعرفها</h2></div>
  <div class="faq"><details class="faq-item"><summary>يقدر يحجز الحصص التجريبية؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. يقدر يشوف المواعيد الفاضية ويحجز الحصة التجريبية على الـ calendar بتاعك. شوف <a href="/integrations">صفحة التكاملات</a> علشان تعرف المتاح دلوقتي.</p></details><details class="faq-item"><summary>يقدر يساعد الأعضاء الجداد يكمّلوا؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. عدنان بيجاوب على أسئلة الكلاسات والمدربين 24 ساعة، وبيحجز ويغيّر مواعيد الكلاسات حسب قواعدك، وبيتابع مع الأعضاء الجداد في أول أسابيعهم.</p></details><details class="faq-item"><summary>بيشتغل مع أكتر من فرع؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. إدّي كل فرع جدوله ومعلوماته، والموظف الذكي بيرد على كل عضو بالمعلومات الصح، بالعربي أو الإنجليزي.</p></details><details class="faq-item"><summary>فريقي يقدر يتدخّل في المحادثة؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>دايمًا. تدخّل بضغطة من موبايلك، وبعدها ارجّع المحادثة للموظف الذكي.</p></details><details class="faq-item"><summary>روز بتبعت رسايل لأعضائنا؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>لأ. روز عمرها ما بترد على الأعضاء ولا بتدخل في محادثة. بتجاوب على أسئلتك في Claude أو ChatGPT، وبتبعتلك تقارير على جدول، وبتغذّي الـ dashboards بتاعتك، فتقدر تدرّب الاستقبال على المتابعة وعرض الاشتراك.</p></details></div>
</div></section>

<section class="s ctaf"><div class="container"><div class="ctaf-card">
  <img class="pg-cta-genu" src="/media/img/genu.svg" alt="" width="96" height="96">
  <div class="eyebrow ctaf-eyebrow">ابدأ دلوقتي</div>
  <h2 style="margin-top:12px;">خلّي الحصص التجريبية تتحجز، وكل عضو يلاقي اللي يهتم بيه.</h2>
  <p class="lead">احجز جلسة تخطيط ونخطّط معاك موظف الاشتراكات الذكي.</p>
  <div class="ctaf-cta"><a href="/contact" class="btn btn-primary btn-lg">احجز جلسة تخطيط</a><a href="https://app.genudo.ai/auth/register" class="ctaf-sec">أو ابدأ مجانًا <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div>
</div></div></section>
</div>`;
export default html;
