// /ind-elearning — value-led rewrite (EN). See docs/website/BUILD-BRIEF.md.
const html = `<div class="pg-ind-elearning">
<section class="phero pind"><div class="container phero-in">
  <div>
    <div class="crumb"><a href="/use-cases">Solutions</a> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg> <span>E-learning & Academies</span></div>
    <h1>Turn course inquiries into enrolled students.</h1>
    <p class="lead">Prospective students ask about courses, fees and start dates at every hour, often at night after work. Your AI employee answers on WhatsApp right away, recommends the right course, explains the payment plan and books the call with your admissions advisor.</p>
    <div class="heroc-cta"><a href="/contact" class="btn btn-primary btn-lg">Book a planning session</a><a href="https://app.genudo.ai/auth/register" class="btn btn-ondark btn-lg">Start free</a></div>
    <div class="pchips"><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5z"/></svg>Course recommendations</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>Advisor calls booked</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>Follow-up that never forgets</span></div>
  </div>
  <div class="phero-media"><div class="pg-hero-ph"><div class="mk mk-phone" role="img" aria-label="WhatsApp chat: a prospective student asks about an evening course and books an advisor call">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">MA</span><div class="mk-phone__who"><b>Mona Adel</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>AI is handling this chat</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>Take over</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">Today</span>
      <div class="mk-msg mk-msg--in">Hi! I want to learn UX design but I work in the daytime. Is there an evening course?<span class="mk-msg__meta">9:40 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Hi Mona! Yes, our UX Foundations track has an evening cohort. Want the duration and the fees?<span class="mk-msg__meta">9:40 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">Yes please. Can I pay in instalments?<span class="mk-msg__meta">9:41 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Yes, you can split it into 3 payments. Shall I book a call with an admissions advisor? I have Wed 4 pm or Thu 6 pm.<span class="mk-msg__meta">9:41 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">Wed 4 pm works<span class="mk-msg__meta">9:42 PM</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">Call booked</div><div class="mk-meeting__when">Wed, 4 pm</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>Bright Path Academy</span><span><i class="mk-ic mk-ic--check"></i>Admissions advisor call</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">AI is handling this chat. Take over to reply.</div>
  </div>
</div></div></div>
</div></section>

<section class="s white-bg"><div class="container">
  <div class="s-head"><span class="eyebrow">What gets in the way</span><h2>Every unanswered question is a lost enrolment.</h2><p class="lead">Choosing a course is a big decision. When answers about fees, schedules and outcomes come late, students hesitate and move on.</p></div>
  <div class="feat-grid" style="margin-top:34px"><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></div><h4>Questions delay enrolment</h4><p>Prospects hesitate when they cannot confirm tuition, schedule or requirements, and the moment passes.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg></div><h4>Your team repeats itself</h4><p>The same admissions questions return every intake and bury your advisors in copy-paste replies.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg></div><h4>Students get stuck</h4><p>Links, schedules, certificates and installments: when nobody answers in time, students lose trust and drop out.</p></div></div>
</div></section>

<section class="s tint-bg" id="fit"><div class="container">
  <div class="s-head"><span class="eyebrow">Your AI team</span><h2>Your AI team in e-learning and academies</h2><p class="lead">Aaref sells, Adnan looks after customers, Roz coaches your team on its WhatsApp conversations. Hire one or all three. Every example is an invented example; every figure links to its source.</p></div>
  <div class="pg-team"><article class="pg-tm pg-tm--aaref"><div class="pg-tm__head"><img src="/media/img/aaref.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Aaref</h3><span class="pg-tm__role">AI sales employee</span></div><a class="pg-go" href="/sol-sales-agent">Meet Aaref <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">Fill the cohort</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>Inquiries go unanswered or get a generic “price sent in DM”; the learner pays whoever explained the course first.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>A graduate asks at 9 pm about a diploma's price and start date. Next afternoon she gets the price only — and pays a competitor whose cohort starts Saturday.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>44% of inquiries to continuing-education units got no reply (<a href="https://upcea.edu/upcea-announces-release-of-new-secret-shopper-benchmarking-study-at-upcea-mems-2025/" target="_blank" rel="noopener"><bdi>UPCEA 2025</bdi></a>). Tailored replies made students 7× more likely to keep engaging (<a href="https://monitor.icef.com/2026/10/getting-past-good-enough-in-responding-to-prospective-students/" target="_blank" rel="noopener"><bdi>Edified via ICEF 2026</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Aaref does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Recommends the right course for the learner's goal and level</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Explains fees, installments and start dates</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Registers the student or books an advisor call, then follows up until the seat is paid</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>Inquiry-to-registration</span><span>Seats filled per cohort</span><span>Response time</span></div></div></div></article>
<article class="pg-tm pg-tm--adnan"><div class="pg-tm__head"><img src="/media/img/adnan.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Adnan</h3><span class="pg-tm__role">AI customer service & success employee</span></div><a class="pg-go" href="/sol-customer-service">Meet Adnan <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">Students who start and stay</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>Students stuck on links, schedules, certificates and installments drop out or lose trust.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>Five minutes before a live session, a student's link isn't working. The reply comes the next day; she misses the class and doesn't continue.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>AI chatbot outreach raised the share of students earning B or better by 5–6 points and reduced course drops (<a href="https://edworkingpapers.com/sites/default/files/ai22-564.pdf" target="_blank" rel="noopener"><bdi>Meyer et al. 2023</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Adnan does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Answers links, schedules, certificates and installment questions instantly</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Solves access and link problems from your schedule and alerts the coordinator</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Welcomes each new student with first steps; escalates sensitive cases</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>Students who start</span><span>Sessions missed</span><span>Questions resolved</span></div></div></div></article>
<article class="pg-tm pg-tm--roz"><div class="pg-tm__head"><img src="/media/img/roz-v2.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Roz</h3><span class="pg-tm__role">AI quality control employee</span></div><a class="pg-go" href="/sol-operations">Meet Roz <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">Advisors who follow up</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>Inquiries read and left unanswered, undecided learners never followed up, advisors quoting different installment plans.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>Before the September cohort, three advisors at a Cairo bootcamp quote three different installment plans; parents asking about certificates are read and left unanswered.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>44% of inquiries to continuing-education units got no reply (<a href="https://upcea.edu/upcea-announces-release-of-new-secret-shopper-benchmarking-study-at-upcea-mems-2025/" target="_blank" rel="noopener"><bdi>UPCEA 2025</bdi></a>); only 1 in 6 UK university inquiries got a follow-up (<a href="https://monitor.icef.com/2021/10/mystery-shopping-study-highlights-lost-opportunity-for-enquiry-conversion/" target="_blank" rel="noopener"><bdi>ICEF 2021</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Roz does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Reports inquiries left unanswered</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Lists undecided learners nobody followed up</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Shows advisors what wins registrations</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>Advisor reply time</span><span>Follow-up rate</span><span>Inquiry-to-registration</span></div></div><p class="pg-tm__note pg-tm__wide">How she works: you ask her in Claude or ChatGPT, she sends scheduled reports and feeds your dashboards. One QR scan per company WhatsApp number links your chats and groups, and she starts the same day.</p></div></article>
</div>
</div></section>

<section class="s white-bg" id="conversation"><div class="container">
  <div class="s-head"><span class="eyebrow">A real conversation</span><h2>From “is there an evening course?” to a booked call.</h2><p class="lead">This is what Aaref does on WhatsApp at 9:40 pm, while your advisors are offline. Fictional data, real flow.</p></div>
  <div class="pg-duo pg-duo--1"><div class="pg-ph"><div class="mk mk-phone" role="img" aria-label="WhatsApp chat: a prospective student asks about an evening course and books an advisor call">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">MA</span><div class="mk-phone__who"><b>Mona Adel</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>AI is handling this chat</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>Take over</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">Today</span>
      <div class="mk-msg mk-msg--in">Hi! I want to learn UX design but I work in the daytime. Is there an evening course?<span class="mk-msg__meta">9:40 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Hi Mona! Yes, our UX Foundations track has an evening cohort. Want the duration and the fees?<span class="mk-msg__meta">9:40 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">Yes please. Can I pay in instalments?<span class="mk-msg__meta">9:41 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Yes, you can split it into 3 payments. Shall I book a call with an admissions advisor? I have Wed 4 pm or Thu 6 pm.<span class="mk-msg__meta">9:41 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">Wed 4 pm works<span class="mk-msg__meta">9:42 PM</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">Call booked</div><div class="mk-meeting__when">Wed, 4 pm</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>Bright Path Academy</span><span><i class="mk-ic mk-ic--check"></i>Admissions advisor call</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">AI is handling this chat. Take over to reply.</div>
  </div>
</div></div></div>
  <ul class="plist pg-proof"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Recommends the course that fits the student’s goal and level</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Explains fees and the payment plan from your own information</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Books the advisor call, so your team starts from a warm student</li></ul>
</div></section>

<section class="s tint-bg" id="followup"><div class="container">
  <div class="prow">
    <div class="prow-copy"><span class="eyebrow">Follow-up</span><h3>The student who went quiet still gets a nudge.</h3><p>Aaref follows up on a schedule you set, in your academy’s tone, and stops when the student replies or the sequence ends. Your advisors only step in when someone is ready.</p></div>
    <div class="prow-media pg-fu"><div class="mk mk-card" role="img" aria-label="Follow-up sequence for a prospective student who went quiet">
  <div class="mk-card__head"><div class="mk-card__title"><i class="mk-ic mk-ic--repeat"></i>Follow-ups · Interested</div><span class="mk-chip mk-chip--green"><i class="mk-dot"></i>Active</span></div>
  <ol class="mk-timeline">
    <li class="mk-step is-sent"><div class="mk-step__head"><b>Follow-up 1</b><span class="mk-step__wait">after 3 hours</span><span class="mk-status mk-status--sent">Sent</span></div><p class="mk-step__msg">Hi Mona, still thinking about the evening UX cohort? Happy to answer anything.</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>Follow-up 2</b><span class="mk-step__wait">after 1 day</span><span class="mk-status mk-status--scheduled">Scheduled</span></div><p class="mk-step__msg">Want me to book a quick call with an admissions advisor?</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>Follow-up 3</b><span class="mk-step__wait">after 3 days</span><span class="mk-status mk-status--scheduled">Scheduled</span></div><p class="mk-step__msg">Last check-in: shall I keep a seat for you in the evening cohort?</p></li>
    <li class="mk-step mk-step--end"><div class="mk-step__head"><i class="mk-ic mk-ic--arrow"></i>No reply after the sequence: move to <span class="mk-stage mk-stage--red mk-stage--sm">Lost</span></div></li>
  </ol>
</div></div>
  </div>
</div></section>

<section class="s white-bg" id="how"><div class="container">
  <div class="s-head"><span class="eyebrow">How it works</span><h2>How you hire your AI team</h2></div>
  <ol class="pg-steps"><li class="pg-step"><span class="pg-n">1</span><div><h4>Plan it together</h4><p>In a planning session we listen to how you work today, and plan together what your AI employee should do and what stays with your team. The build time is agreed in that session.</p></div></li><li class="pg-step"><span class="pg-n">2</span><div><h4>We build and launch</h4><p>Our automation specialist builds your employee from your own information, then launches it on your WhatsApp.</p></div></li><li class="pg-step"><span class="pg-n">3</span><div><h4>We improve it with you</h4><p>Your account manager reviews the results with you and keeps tuning. Your team sees every chat in one inbox and can step in with one tap.</p></div></li></ol>
  <p class="pg-control">You stay in control. Take over any chat in one tap from your phone and hand it back when you are done. Roz needs no build: log in, scan one QR code per company WhatsApp number, and she starts the same day.</p>
</div></section>

<section class="s tint-bg"><div class="container">
  <div class="s-head center"><span class="eyebrow">Questions</span><h2>Good to know</h2></div>
  <div class="faq"><details class="faq-item"><summary>Can it recommend the right course?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. It asks about the student’s goals and level, then recommends from the course information you gave it, and offers to book an advisor call.</p></details><details class="faq-item"><summary>Can it explain fees and installments?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. It explains fees, installments and start dates from your own information, in the student’s language: Arabic or English.</p></details><details class="faq-item"><summary>What if it does not know the answer?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>It answers only from what you have given it. Anything else goes to your team, and you can take over the chat at any time.</p></details><details class="faq-item"><summary>Can it help students after they enroll?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. Adnan answers links, schedules, certificates and installment questions instantly, solves access problems from your schedule and alerts your coordinator.</p></details><details class="faq-item"><summary>Can it connect to our calendar or CRM?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. It can look up free slots, book calls and update your CRM. See the <a href="/integrations">integrations page</a> for what connects today.</p></details><details class="faq-item"><summary>Does Roz message our students?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>No. Roz never replies to students and never steps into a chat. She answers your questions in Claude or ChatGPT, sends scheduled reports and feeds your dashboards, so you can coach advisors on reply time and follow-up.</p></details></div>
</div></section>

<section class="s ctaf"><div class="container"><div class="ctaf-card">
  <img class="pg-cta-genu" src="/media/img/genu.svg" alt="" width="96" height="96">
  <div class="eyebrow ctaf-eyebrow">Get started</div>
  <h2 style="margin-top:12px;">Every prospect gets an answer. Every interested one gets followed up.</h2>
  <p class="lead">Book a planning session and we will plan your admissions AI employee with you.</p>
  <div class="ctaf-cta"><a href="/contact" class="btn btn-primary btn-lg">Book a planning session</a><a href="https://app.genudo.ai/auth/register" class="ctaf-sec">or start free <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div>
</div></div></section>
</div>`;
export default html;
