// /ind-elearning — value-led rewrite (AR, Egyptian, primary). See docs/website/BUILD-BRIEF.md.
const html = `<div class="pg-ind-elearning">
<section class="phero pind"><div class="container phero-in">
  <div>
    <div class="crumb"><a href="/use-cases">الحلول</a> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg> <span>التعليم الإلكتروني والأكاديميات</span></div>
    <h1>الاستفسار يتحوّل لطالب مسجّل.</h1>
    <p class="lead">الطلاب بيسألوا عن الكورسات والمصاريف وميعاد البداية في أي وقت، وكتير منهم بالليل بعد الشغل. موظفك الذكي بيرد عليهم على <bdi>WhatsApp</bdi> على طول، يرشّحلهم الكورس المناسب، يشرحلهم خطة الدفع، ويحجزلهم المكالمة مع مستشار القبول عندك.</p>
    <div class="heroc-cta"><a href="/contact" class="btn btn-primary btn-lg">احجز جلسة تخطيط</a><a href="https://app.genudo.ai/auth/register" class="btn btn-ondark btn-lg">ابدأ مجانًا</a></div>
    <div class="pchips"><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5z"/></svg>ترشيح الكورس المناسب</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>حجز مكالمات المستشار</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>متابعة مش بتنسى</span></div>
  </div>
  <div class="phero-media"><div class="pg-hero-ph"><div class="mk mk-phone" dir="rtl" lang="ar" role="img" aria-label="محادثة WhatsApp: طالبة محتملة بتسأل عن كورس مسائي وبتحجز مكالمة مع المستشارة">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">م</span><div class="mk-phone__who"><b>منى عادل</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>الموظف الذكي بيتولّى المحادثة دي</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>تدخّل بشري</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">اليوم</span>
      <div class="mk-msg mk-msg--in">السلام عليكم، عايزة أتعلم تصميم <bdi>UX</bdi> بس بشتغل الصبح. فيه كورس بالليل؟<span class="mk-msg__meta"><bdi>9:40</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>أهلًا يا منى! أيوه، كورس أساسيات الـ <bdi>UX</bdi> عندنا بدفعة مسائية. تحبي أقولك المدة والمصاريف؟<span class="mk-msg__meta"><bdi>9:40</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">أيوه، وينفع أقسّط؟<span class="mk-msg__meta"><bdi>9:41</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>ينفع تقسّطي على <bdi>3</bdi> دفعات. تحبي أحجزلك مكالمة مع مستشارة القبول؟ عندي الأربع الساعة <bdi>4</bdi> أو الخميس الساعة <bdi>6</bdi>.<span class="mk-msg__meta"><bdi>9:41</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">الأربع الساعة <bdi>4</bdi> كويس<span class="mk-msg__meta"><bdi>9:42</bdi> م</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">الموعد اتحجز</div><div class="mk-meeting__when">الأربع، <bdi>4</bdi> م</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>أكاديمية برايت باث</span><span><i class="mk-ic mk-ic--check"></i>مكالمة مع مستشارة القبول</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">الموظف الذكي بيتولّى المحادثة دي. اضغط «تدخّل بشري» عشان ترد بنفسك.</div>
  </div>
</div></div></div>
</div></section>

<section class="s white-bg"><div class="container">
  <div class="s-head"><span class="eyebrow">اللي بيعطّلك</span><h2>كل سؤال من غير رد بيضيّع طالب.</h2><p class="lead">اختيار الكورس قرار كبير. لما الرد على المصاريف والمواعيد والنتائج بيتأخر، الطالب بيتردد وبيروح لغيرك.</p></div>
  <div class="feat-grid" style="margin-top:34px"><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></div><h4>الأسئلة بتأخّر التسجيل</h4><p>المهتم بيتردد لما ما يقدرش يتأكد من المصاريف أو الجدول أو الشروط، واللحظة بتعدّي.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg></div><h4>فريقك بيعيد نفس الكلام</h4><p>نفس أسئلة القبول بترجع مع كل دفعة وبتغرّق المستشارين في ردود متكررة.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg></div><h4>الطالب بيتعطّل</h4><p>الروابط والمواعيد والشهادات والأقساط: لما محدش يرد في وقتها، الطالب بيفقد الثقة وبيسيب الكورس.</p></div></div>
</div></section>

<section class="s tint-bg" id="fit"><div class="container">
  <div class="s-head"><span class="eyebrow">فريقك الذكي</span><h2>فريقك الذكي في التعليم الإلكتروني والأكاديميات</h2><p class="lead">عارف بيبيع، وعدنان بيهتم بالعملاء، وروز بتساعد فريقك يحسّن محادثاته على واتساب. وظّف واحد منهم أو التلاتة. كل مثال هنا مثال افتراضي، وكل رقم معاه رابط مصدره.</p></div>
  <div class="pg-team"><article class="pg-tm pg-tm--aaref"><div class="pg-tm__head"><img src="/media/img/aaref.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>عارف</h3><span class="pg-tm__role">موظف مبيعات ذكي</span></div><a class="pg-go" href="/sol-sales-agent">اتعرف على عارف <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">كل دفعة مكتملة</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>الاستفسارات بتفضل من غير رد أو بيترد عليها بـ«السعر في الخاص»، والطالب بيسجّل عند اللي وضّحله تفاصيل الكورس الأول.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>خريجة بتسأل الساعة 9 بالليل عن سعر دبلومة وميعاد بدايتها. تاني يوم بعد الضهر بيوصلها السعر بس — فبتسجّل عند منافس دفعته بتبدأ السبت.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>44% من الاستفسارات لوحدات التعليم المستمر ما اترد عليهاش (<a href="https://upcea.edu/upcea-announces-release-of-new-secret-shopper-benchmarking-study-at-upcea-mems-2025/" target="_blank" rel="noopener"><bdi>UPCEA 2025</bdi></a>). والرد المخصص زوّد استمرار الطلاب في التواصل 7 أضعاف (<a href="https://monitor.icef.com/2026/10/getting-past-good-enough-in-responding-to-prospective-students/" target="_blank" rel="noopener"><bdi>ICEF 2026</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بيعمله عارف</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيرشّح الكورس المناسب لهدف الطالب ومستواه</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيوضّح الأسعار والتقسيط ومواعيد البداية</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيسجّل الطالب أو يحجز مكالمة مع المستشار، ويتابع لحد إتمام الدفع</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>من استفسار لتسجيل</span><span>الأماكن المحجوزة في كل دفعة</span><span>سرعة الرد</span></div></div></div></article>
<article class="pg-tm pg-tm--adnan"><div class="pg-tm__head"><img src="/media/img/adnan.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>عدنان</h3><span class="pg-tm__role">موظف خدمة ونجاح عملاء ذكي</span></div><a class="pg-go" href="/sol-customer-service">اتعرف على عدنان <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">طلاب بيبدأوا ويكمّلوا</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>الطلاب اللي بيواجهوا مشاكل في الروابط والمواعيد والشهادات والأقساط بيوقفوا أو بيفقدوا الثقة.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>قبل المحاضرة اللايف بخمس دقايق، الرابط عند طالبة مش شغال. الرد بييجي تاني يوم، فبتفوّت المحاضرة وما بتكمّلش.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>رسائل متابعة بشات بوت ذكاء اصطناعي رفعت نسبة الطلاب الحاصلين على B أو أعلى من 5 لـ 6 نقاط، وقلّلت الانسحاب من الكورسات (<a href="https://edworkingpapers.com/sites/default/files/ai22-564.pdf" target="_blank" rel="noopener"><bdi>Meyer et al. 2023</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بيعمله عدنان</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيجاوب على الروابط والمواعيد والشهادات والأقساط فورًا</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحل مشاكل الدخول والروابط من جدولك، ويبلّغ منسق الكورس</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيرحّب بكل طالب جديد بأول خطوات، ويصعّد الحالات الحساسة</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>طلاب بدأوا</span><span>محاضرات اتفوّتت</span><span>أسئلة اتحلت</span></div></div></div></article>
<article class="pg-tm pg-tm--roz"><div class="pg-tm__head"><img src="/media/img/roz-v2.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>روز</h3><span class="pg-tm__role">موظفة مراقبة جودة ذكية</span></div><a class="pg-go" href="/sol-operations">اتعرف على روز <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">مستشارين بيتابعوا</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>المشكلة</h4><p>استفسارات اتقرت من غير رد، وطلاب مترددين محدش تابع معاهم، ومستشارين بيعرضوا خطط تقسيط مختلفة.</p></div><div class="pg-tm__cell"><h4>مثال افتراضي</h4><p>قبل دفعة سبتمبر، 3 مستشارين في أكاديمية برمجة في القاهرة بيعرضوا 3 خطط تقسيط مختلفة، وأسئلة أولياء الأمور عن الشهادات اتقرت من غير رد.</p></div><div class="pg-tm__cell"><h4>الدليل</h4><p>44% من الاستفسارات لوحدات التعليم المستمر ما اترد عليهاش (<a href="https://upcea.edu/upcea-announces-release-of-new-secret-shopper-benchmarking-study-at-upcea-mems-2025/" target="_blank" rel="noopener"><bdi>UPCEA 2025</bdi></a>)، واستفسار واحد بس من كل 6 لجامعات UK اتعمله متابعة (<a href="https://monitor.icef.com/2021/10/mystery-shopping-study-highlights-lost-opportunity-for-enquiry-conversion/" target="_blank" rel="noopener"><bdi>ICEF 2021</bdi></a>).</p></div><div class="pg-tm__cell"><h4>اللي بتعمله روز</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بتوضّح في التقارير الاستفسارات اللي من غير رد</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بتحدد الطلاب المترددين اللي محدش تابع معاهم</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بتوضّح للمستشارين الأسلوب اللي بيحقق تسجيلات</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>أرقام تتابعها</h4><div class="pg-tm__nw"><span>سرعة رد المستشارين</span><span>نسبة المتابعة</span><span>من استفسار لتسجيل</span></div></div><p class="pg-tm__note pg-tm__wide">طريقة شغلها: بتسألها في Claude أو ChatGPT، وبتبعتلك تقارير على جدول، وبتغذّي الـ dashboards بتاعتك. مسح كود QR واحد لكل رقم واتساب للشركة بيربط محادثاتك وجروباتك، وبتبدأ في نفس اليوم.</p></div></article>
</div>
</div></section>

<section class="s white-bg" id="conversation"><div class="container">
  <div class="s-head"><span class="eyebrow">محادثة حقيقية</span><h2>من «فيه كورس بالليل؟» لحد مكالمة متحجزة.</h2><p class="lead">ده اللي عارف بيعمله على <bdi>WhatsApp</bdi> الساعة <bdi>9:40</bdi> بالليل، والمستشارين أوفلاين. بيانات تخيلية، بس الخطوات حقيقية.</p></div>
  <div class="pg-duo pg-duo--1"><div class="pg-ph"><div class="mk mk-phone" dir="rtl" lang="ar" role="img" aria-label="محادثة WhatsApp: طالبة محتملة بتسأل عن كورس مسائي وبتحجز مكالمة مع المستشارة">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">م</span><div class="mk-phone__who"><b>منى عادل</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>الموظف الذكي بيتولّى المحادثة دي</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>تدخّل بشري</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">اليوم</span>
      <div class="mk-msg mk-msg--in">السلام عليكم، عايزة أتعلم تصميم <bdi>UX</bdi> بس بشتغل الصبح. فيه كورس بالليل؟<span class="mk-msg__meta"><bdi>9:40</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>أهلًا يا منى! أيوه، كورس أساسيات الـ <bdi>UX</bdi> عندنا بدفعة مسائية. تحبي أقولك المدة والمصاريف؟<span class="mk-msg__meta"><bdi>9:40</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">أيوه، وينفع أقسّط؟<span class="mk-msg__meta"><bdi>9:41</bdi> م</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>عارف · موظف ذكي</span>ينفع تقسّطي على <bdi>3</bdi> دفعات. تحبي أحجزلك مكالمة مع مستشارة القبول؟ عندي الأربع الساعة <bdi>4</bdi> أو الخميس الساعة <bdi>6</bdi>.<span class="mk-msg__meta"><bdi>9:41</bdi> م <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">الأربع الساعة <bdi>4</bdi> كويس<span class="mk-msg__meta"><bdi>9:42</bdi> م</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">الموعد اتحجز</div><div class="mk-meeting__when">الأربع، <bdi>4</bdi> م</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>أكاديمية برايت باث</span><span><i class="mk-ic mk-ic--check"></i>مكالمة مع مستشارة القبول</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">الموظف الذكي بيتولّى المحادثة دي. اضغط «تدخّل بشري» عشان ترد بنفسك.</div>
  </div>
</div></div></div>
  <ul class="plist pg-proof"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيرشّح الكورس اللي يناسب هدف الطالب ومستواه</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيشرح المصاريف وخطة الدفع من معلوماتك إنت</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>بيحجز مكالمة المستشار، ففريقك بيبدأ مع طالب مهتم فعلًا</li></ul>
</div></section>

<section class="s tint-bg" id="followup"><div class="container">
  <div class="prow">
    <div class="prow-copy"><span class="eyebrow">المتابعة</span><h3>الطالب اللي سكت لسه بيوصله تذكير.</h3><p>عارف بيتابع على جدول إنت بتحدده، بأسلوب أكاديميتك، وبيوقف لما الطالب يرد أو التسلسل يخلص. المستشارين بيدخلوا بس لما حد يبقى جاهز.</p></div>
    <div class="prow-media pg-fu"><div class="mk mk-card" dir="rtl" lang="ar" role="img" aria-label="تسلسل المتابعات لطالبة محتملة سكتت">
  <div class="mk-card__head"><div class="mk-card__title"><i class="mk-ic mk-ic--repeat"></i>المتابعات · مهتم</div><span class="mk-chip mk-chip--green"><i class="mk-dot"></i>نشطة</span></div>
  <ol class="mk-timeline">
    <li class="mk-step is-sent"><div class="mk-step__head"><b>المتابعة 1</b><span class="mk-step__wait">بعد 3 ساعات</span><span class="mk-status mk-status--sent">مُرسلة</span></div><p class="mk-step__msg">أهلًا يا منى، لسه بتفكري في دفعة الـ <bdi>UX</bdi> المسائية؟ أنا موجود لو عندك أي سؤال.</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>المتابعة 2</b><span class="mk-step__wait">بعد يوم واحد</span><span class="mk-status mk-status--scheduled">مجدولة</span></div><p class="mk-step__msg">تحبي أحجزلك مكالمة سريعة مع مستشارة القبول؟</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>المتابعة 3</b><span class="mk-step__wait">بعد 3 أيام</span><span class="mk-status mk-status--scheduled">مجدولة</span></div><p class="mk-step__msg">آخر تذكير: أسيبلك مكان في الدفعة المسائية؟</p></li>
    <li class="mk-step mk-step--end"><div class="mk-step__head"><i class="mk-ic mk-ic--arrow"></i>لا رد بعد انتهاء التسلسل: النقل إلى <span class="mk-stage mk-stage--red mk-stage--sm">ضائعة</span></div></li>
  </ol>
</div></div>
  </div>
</div></section>

<section class="s white-bg" id="how"><div class="container">
  <div class="s-head"><span class="eyebrow">بيشتغل إزاي</span><h2>إزاي بتوظّف فريقك الذكي</h2></div>
  <ol class="pg-steps"><li class="pg-step"><span class="pg-n">1</span><div><h4>خطّطوا مع بعض</h4><p>في جلسة التخطيط بنسمعك وبنفهم شغلك النهارده، ونخطّط معاك الموظف هيعمل إيه واللي يفضل عند فريقك. ومدة التنفيذ بنتفق عليها في الجلسة دي.</p></div></li><li class="pg-step"><span class="pg-n">2</span><div><h4>بنبني ونطلق</h4><p>متخصص الـ automation بيبني موظفك من معلوماتك إنت، وبعدين بيشتغل على الـ WhatsApp بتاعك.</p></div></li><li class="pg-step"><span class="pg-n">3</span><div><h4>بنحسّن معاك</h4><p>الـ account manager بيراجع النتايج معاك وبيفضل يظبط. وفريقك بيشوف كل المحادثات في الـ inbox واحد ويتدخّل بضغطة.</p></div></li></ol>
  <p class="pg-control">إنت اللي ماسك الدفة. تدخّل في أي محادثة بضغطة من موبايلك، وارجّعها للموظف لما تخلص. روز مش محتاجة تنفيذ: سجّل دخول، وامسح كود QR واحد لكل رقم واتساب للشركة، وبتبدأ في نفس اليوم.</p>
</div></section>

<section class="s tint-bg"><div class="container">
  <div class="s-head center"><span class="eyebrow">أسئلة</span><h2>حاجات تحب تعرفها</h2></div>
  <div class="faq"><details class="faq-item"><summary>يقدر يرشّح الكورس المناسب؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. بيسأل عن هدف الطالب ومستواه، وبعدين يرشّح من معلومات الكورسات اللي إنت إديتهاله، ويعرض يحجز مكالمة مع المستشار.</p></details><details class="faq-item"><summary>يقدر يشرح المصاريف والتقسيط؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. بيشرح المصاريف والتقسيط ومواعيد البداية من معلوماتك إنت، بلغة الطالب: عربي أو إنجليزي.</p></details><details class="faq-item"><summary>لو معرفش الإجابة؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>بيجاوب بس من اللي إنت إديتهوله. أي حاجة تانية بتروح لفريقك، وتقدر تتدخّل في المحادثة في أي وقت.</p></details><details class="faq-item"><summary>يقدر يساعد الطلاب بعد التسجيل؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. عدنان بيجاوب فورًا على أسئلة الروابط والمواعيد والشهادات والأقساط، وبيحل مشاكل الدخول من جدولك وبيبلّغ منسق الكورس.</p></details><details class="faq-item"><summary>ينفع يتربط بالـ calendar أو الـ CRM عندنا؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>أيوه. يقدر يشوف المواعيد الفاضية ويحجز المكالمات ويحدّث الـ CRM. شوف <a href="/integrations">صفحة التكاملات</a> علشان تعرف المتاح دلوقتي.</p></details><details class="faq-item"><summary>روز بتبعت رسايل لطلابنا؟<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>لأ. روز عمرها ما بترد على الطلاب ولا بتدخل في محادثة. بتجاوب على أسئلتك في Claude أو ChatGPT، وبتبعتلك تقارير على جدول، وبتغذّي الـ dashboards بتاعتك، فتقدر تدرّب المستشارين على سرعة الرد والمتابعة.</p></details></div>
</div></section>

<section class="s ctaf"><div class="container"><div class="ctaf-card">
  <img class="pg-cta-genu" src="/media/img/genu.svg" alt="" width="96" height="96">
  <div class="eyebrow ctaf-eyebrow">ابدأ دلوقتي</div>
  <h2 style="margin-top:12px;">كل مهتم يلاقي رد. وكل مهتم بجد يتتابع.</h2>
  <p class="lead">احجز جلسة تخطيط ونخطّط معاك موظف القبول الذكي.</p>
  <div class="ctaf-cta"><a href="/contact" class="btn btn-primary btn-lg">احجز جلسة تخطيط</a><a href="https://app.genudo.ai/auth/register" class="ctaf-sec">أو ابدأ مجانًا <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div>
</div></div></section>
</div>`;
export default html;
