// /ind-fitness — value-led rewrite (EN). See docs/website/BUILD-BRIEF.md.
const html = `<div class="pg-ind-fitness">
<section class="phero pind"><div class="container phero-in">
  <div>
    <div class="crumb"><a href="/use-cases">Solutions</a> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg> <span>Fitness Centres</span></div>
    <h1>Trials get booked, memberships get answered, and the front desk focuses on members.</h1>
    <p class="lead">Questions about classes and plans arrive on WhatsApp at every hour. Your AI employee, trained on your gym, books the trial class, answers membership questions and follows up until the membership is paid, so nobody waits and your team stays on the floor.</p>
    <div class="heroc-cta"><a href="/contact" class="btn btn-primary btn-lg">Book a planning session</a><a href="https://app.genudo.ai/auth/register" class="btn btn-ondark btn-lg">Start free</a></div>
    <div class="pchips"><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>Trial bookings</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></svg>Membership questions</span><span class="pchip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg>Reminders & follow-up</span></div>
  </div>
  <div class="phero-media"><div class="pg-hero-ph"><div class="mk mk-phone" role="img" aria-label="WhatsApp chat: a visitor books a trial class">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">KS</span><div class="mk-phone__who"><b>Karim Saeed</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>AI is handling this chat</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>Take over</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">Today</span>
      <div class="mk-msg mk-msg--in">Hi! I want to try a CrossFit class before I join. Is that possible?<span class="mk-msg__meta">6:20 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Hi Karim! Of course. I have tomorrow 7 pm or 8:30 pm. Which one suits you?<span class="mk-msg__meta">6:20 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">7 pm works<span class="mk-msg__meta">6:21 PM</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">Trial class booked</div><div class="mk-meeting__when">Wed, 7 pm</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>Prime Fit Gym</span><span><i class="mk-ic mk-ic--check"></i>Trial class</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">AI is handling this chat. Take over to reply.</div>
  </div>
</div></div></div>
</div></section>

<section class="s white-bg"><div class="container">
  <div class="s-head"><span class="eyebrow">What gets in the way</span><h2>Wellness is personal, and people expect a fast answer.</h2><p class="lead">When someone is choosing a gym or booking a class, a slow reply costs you a signup.</p></div>
  <div class="feat-grid" style="margin-top:34px"><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 8v4l3 2"/></svg></div><h4>Questions block bookings</h4><p>People give up when they cannot quickly confirm class details, pricing or availability.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 2 4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg></div><h4>The front desk answers the same thing all day</h4><p>Coaches and reception lose hours to the same questions about schedules, policies and memberships.</p></div><div class="featc"><div class="oi" style="background:#e2562a"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/></svg></div><h4>New members drift away</h4><p>A new member with no answers about classes and trainers stops coming within weeks, and the membership goes with them.</p></div></div>
</div></section>

<section class="s tint-bg" id="fit"><div class="container">
  <div class="s-head"><span class="eyebrow">Your AI team</span><h2>Your AI team in fitness centres</h2><p class="lead">Aaref sells, Adnan looks after customers, Roz coaches your team on its WhatsApp conversations. Hire one or all three. Every example is an invented example; every figure links to its source.</p></div>
  <div class="pg-team"><article class="pg-tm pg-tm--aaref"><div class="pg-tm__head"><img src="/media/img/aaref.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Aaref</h3><span class="pg-tm__role">AI sales employee</span></div><a class="pg-go" href="/sol-sales-agent">Meet Aaref <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">Turn “how much?” into members</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>Price questions answered tomorrow; trial-takers and walk-ins never followed up.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>First week of January in Maadi: dozens of “how much?” messages an hour. A trial is booked, no reminder is sent, nobody follows up.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>Web inquiries were answered within 24 hours only 61% of the time, and only 35% of prospects were contacted within the club's own target (<a href="https://www.healthclubmanagement.co.uk/health-club-management-features/Only-60-of-in-person-gym-membership-enquiries-are-asked-for-contact-details/30424" target="_blank" rel="noopener"><bdi>UK mystery shop, 500+ clubs</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Aaref does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Answers packages, classes and offers around the clock</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Books the trial session or signs the member up</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Follows up after the trial until the membership is paid</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>Trial-to-member rate</span><span>New members a month</span><span>Response time</span></div></div></div></article>
<article class="pg-tm pg-tm--adnan"><div class="pg-tm__head"><img src="/media/img/adnan.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Adnan</h3><span class="pg-tm__role">AI customer service & success employee</span></div><a class="pg-go" href="/sol-customer-service">Meet Adnan <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">Members who stay</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>New members drop out early; class and trainer questions pile up; the same schedule questions all day.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>A new member asks at 10 pm which class suits a beginner and how to book it. Nobody answers; by week three she has stopped coming.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>63% of new gym members quit before month 3, and fewer than 4% stay a year (<a href="https://pubmed.ncbi.nlm.nih.gov/26874647/" target="_blank" rel="noopener"><bdi>Sperandei et al. 2016</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Adnan does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Answers schedules, classes and trainer questions around the clock</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Books and changes class slots by your rules, and keeps the desk informed</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Checks in with new members in their first weeks</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>3-month retention</span><span>Class bookings</span><span>Front-desk messages</span></div></div></div></article>
<article class="pg-tm pg-tm--roz"><div class="pg-tm__head"><img src="/media/img/roz-v2.svg" alt="" width="56" height="61"><div class="pg-tm__who"><h3>Roz</h3><span class="pg-tm__role">AI quality control employee</span></div><a class="pg-go" href="/sol-operations">Meet Roz <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div><p class="pg-tm__title">A front desk that sells</p><div class="pg-tm__grid"><div class="pg-tm__cell"><h4>The problem</h4><p>Trial visitors never called, prices quoted differently, member questions unanswered for days.</p></div><div class="pg-tm__cell"><h4>Invented example</h4><p>A Sheikh Zayed gym launches a summer offer: three prices on WhatsApp, trial visitors never called, a member's question unanswered for a week.</p></div><div class="pg-tm__cell"><h4>The evidence</h4><p>Only 35% of prospects were contacted within the club's own target, and they were asked to join only 56% of the time (<a href="https://www.healthclubmanagement.co.uk/health-club-management-features/Only-60-of-in-person-gym-membership-enquiries-are-asked-for-contact-details/30424" target="_blank" rel="noopener"><bdi>UK mystery shop, 500+ clubs</bdi></a>).</p></div><div class="pg-tm__cell"><h4>What Roz does</h4><ul class="plist"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Reports trial visitors and prospects with no follow-up</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Shows member questions left unanswered</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Coaching insights so the desk asks for the sale</li></ul></div><div class="pg-tm__cell pg-tm__wide"><h4>Numbers to watch</h4><div class="pg-tm__nw"><span>Follow-up within 48 h</span><span>Trial-to-member rate</span><span>Questions answered</span></div></div><p class="pg-tm__note pg-tm__wide">How she works: you ask her in Claude or ChatGPT, she sends scheduled reports and feeds your dashboards. One QR scan per company WhatsApp number links your chats and groups, and she starts the same day.</p></div></article>
</div>
</div></section>

<section class="s white-bg" id="conversation"><div class="container">
  <div class="s-head"><span class="eyebrow">Real conversations</span><h2>A trial class booked and a new member helped, over WhatsApp.</h2><p class="lead">Two chats your front desk no longer has to answer by hand. Invented example, real flow.</p></div>
  <div class="pg-duo pg-duo--2"><div class="pg-ph"><div class="mk mk-phone" role="img" aria-label="WhatsApp chat: a visitor books a trial class">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">KS</span><div class="mk-phone__who"><b>Karim Saeed</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>AI is handling this chat</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>Take over</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">Today</span>
      <div class="mk-msg mk-msg--in">Hi! I want to try a CrossFit class before I join. Is that possible?<span class="mk-msg__meta">6:20 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Aaref · AI</span>Hi Karim! Of course. I have tomorrow 7 pm or 8:30 pm. Which one suits you?<span class="mk-msg__meta">6:20 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">7 pm works<span class="mk-msg__meta">6:21 PM</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">Trial class booked</div><div class="mk-meeting__when">Wed, 7 pm</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>Prime Fit Gym</span><span><i class="mk-ic mk-ic--check"></i>Trial class</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">AI is handling this chat. Take over to reply.</div>
  </div>
</div></div><div class="pg-ph"><div class="mk mk-phone" role="img" aria-label="WhatsApp chat: a new member asks which class suits a beginner and is booked in">
  <div class="mk-phone__screen">
    <div class="mk-phone__head"><i class="mk-ic mk-ic--back"></i><span class="mk-avatar mk-avatar--green">MA</span><div class="mk-phone__who"><b>Mona Adel</b><span><i class="mk-ic mk-ic--whatsapp"></i><bdi>WhatsApp · +20 100 000 0000</bdi></span></div></div>
    <div class="mk-takeover"><span class="mk-takeover__state"><i class="mk-ic mk-ic--sparkle"></i>AI is handling this chat</span><span class="mk-takeover__btn"><i class="mk-ic mk-ic--pause"></i>Take over</span></div>
    <div class="mk-chat">
      <span class="mk-chat__day">Today</span>
      <div class="mk-msg mk-msg--in">Hi! Which class is best for a beginner? And how do I book it?<span class="mk-msg__meta">10:02 PM</span></div>
      <div class="mk-msg mk-msg--out"><span class="mk-msg__by"><i class="mk-ic mk-ic--sparkle"></i>Adnan · AI</span>Welcome, Mona! For a beginner I suggest the Foundations class, Tuesdays and Thursdays at 7 pm. Shall I book you in for this Thursday?<span class="mk-msg__meta">10:02 PM <i class="mk-ic mk-ic--checks"></i></span></div>
      <div class="mk-msg mk-msg--in">Yes please<span class="mk-msg__meta">10:03 PM</span></div>
      <div class="mk-meeting"><div class="mk-meeting__top"><span class="mk-meeting__ic"><i class="mk-ic mk-ic--calendar"></i></span><div><div class="mk-meeting__title">Class booked</div><div class="mk-meeting__when">Thu, 7 pm</div></div></div><div class="mk-meeting__rows"><span><i class="mk-ic mk-ic--check"></i>Foundations class</span><span><i class="mk-ic mk-ic--check"></i>Front desk informed</span></div></div>
      <div class="mk-typing mk-typing--in"><i></i><i></i><i></i></div>
    </div>
    <div class="mk-phone__compose">AI is handling this chat. Take over to reply.</div>
  </div>
</div></div></div>
  <ul class="plist pg-proof"><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Books the trial class straight into your schedule</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Answers from your own plans and policies, never from guesswork</li><li><span class="ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 5 5L20 7"/></svg></span>Passes anything sensitive to your front desk with the details already collected</li></ul>
</div></section>

<section class="s tint-bg" id="followup"><div class="container">
  <div class="prow">
    <div class="prow-copy"><span class="eyebrow">Follow-up</span><h3>A trial visitor who has not signed up still hears from you.</h3><p>After the trial, Aaref checks in on a schedule you set, in your club’s tone, and stops when the person replies or the sequence ends. Your team steps in when someone is ready to join.</p></div>
    <div class="prow-media pg-fu"><div class="mk mk-card" role="img" aria-label="Follow-up sequence after a trial class">
  <div class="mk-card__head"><div class="mk-card__title"><i class="mk-ic mk-ic--repeat"></i>Follow-ups · Trial class</div><span class="mk-chip mk-chip--green"><i class="mk-dot"></i>Active</span></div>
  <ol class="mk-timeline">
    <li class="mk-step is-sent"><div class="mk-step__head"><b>Follow-up 1</b><span class="mk-step__wait">after 3 hours</span><span class="mk-status mk-status--sent">Sent</span></div><p class="mk-step__msg">Hi Karim, how was your first class? Want me to walk you through the membership options?</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>Follow-up 2</b><span class="mk-step__wait">after 1 day</span><span class="mk-status mk-status--scheduled">Scheduled</span></div><p class="mk-step__msg">Want me to book you a second class this week?</p></li>
    <li class="mk-step is-scheduled"><div class="mk-step__head"><b>Follow-up 3</b><span class="mk-step__wait">after 3 days</span><span class="mk-status mk-status--scheduled">Scheduled</span></div><p class="mk-step__msg">Last check-in: shall I keep a spot for you this week?</p></li>
    <li class="mk-step mk-step--end"><div class="mk-step__head"><i class="mk-ic mk-ic--arrow"></i>No reply after the sequence: move to <span class="mk-stage mk-stage--red mk-stage--sm">Lost</span></div></li>
  </ol>
</div></div>
  </div>
</div></section>

<section class="s white-bg" id="how"><div class="container">
  <div class="s-head"><span class="eyebrow">How it works</span><h2>How you hire your AI team</h2></div>
  <ol class="pg-steps"><li class="pg-step"><span class="pg-n">1</span><div><h4>Plan it together</h4><p>In a planning session we listen to how you work today, and plan together what your AI employee should do and what stays with your team. The build time is agreed in that session.</p></div></li><li class="pg-step"><span class="pg-n">2</span><div><h4>We build and launch</h4><p>Our automation specialist builds your employee from your own information, then launches it on your WhatsApp.</p></div></li><li class="pg-step"><span class="pg-n">3</span><div><h4>We improve it with you</h4><p>Your account manager reviews the results with you and keeps tuning. Your team sees every chat in one inbox and can step in with one tap.</p></div></li></ol>
  <p class="pg-control">You stay in control. Take over any chat in one tap from your phone and hand it back when you are done. Roz needs no build: log in, scan one QR code per company WhatsApp number, and she starts the same day.</p>
</div></section>

<section class="s tint-bg"><div class="container">
  <div class="s-head center"><span class="eyebrow">Questions</span><h2>Good to know</h2></div>
  <div class="faq"><details class="faq-item"><summary>Can it book trial classes?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. It can look up free slots and book the trial into your calendar. See the <a href="/integrations">integrations page</a> for what connects today.</p></details><details class="faq-item"><summary>Can it help new members stay?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. Adnan answers class and trainer questions around the clock, books and changes class slots by your rules, and checks in with new members in their first weeks.</p></details><details class="faq-item"><summary>Does it work across several branches?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Yes. Give each branch its own timetable and facts, and the AI answers each member with the right ones, in Arabic or English.</p></details><details class="faq-item"><summary>Can my team take over a chat?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>Always. Take over in one tap from your phone, then hand the chat back to the AI.</p></details><details class="faq-item"><summary>Does Roz message our members?<span class="pm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg></span></summary><p>No. Roz never replies to members and never steps into a chat. She answers your questions in Claude or ChatGPT, sends scheduled reports and feeds your dashboards, so you can coach the front desk to follow up and ask for the sale.</p></details></div>
</div></section>

<section class="s ctaf"><div class="container"><div class="ctaf-card">
  <img class="pg-cta-genu" src="/media/img/genu.svg" alt="" width="96" height="96">
  <div class="eyebrow ctaf-eyebrow">Get started</div>
  <h2 style="margin-top:12px;">Keep trials booked and members looked after.</h2>
  <p class="lead">Book a planning session and we will plan your membership AI employee with you.</p>
  <div class="ctaf-cta"><a href="/contact" class="btn btn-primary btn-lg">Book a planning session</a><a href="https://app.genudo.ai/auth/register" class="ctaf-sec">or start free <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14M13 6l6 6-6 6"/></svg></a></div>
</div></div></section>
</div>`;
export default html;
