import type { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';
import { routing } from './routing';

/**
 * SEO / GEO helpers — one place for canonical URLs, hreflang alternates,
 * localized metadata, and JSON-LD. Everything is locale-aware and works for
 * ANY locale added to `routing.locales` (no per-language edits needed).
 *
 * Set NEXT_PUBLIC_SITE_URL in the deploy env to the production origin.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://genudo.ai').replace(/\/$/, '');

/** OG `og:locale` tag per app locale. */
const OG_LOCALE: Record<string, string> = { en: 'en_US', 'ar-EG': 'ar_EG', 'ar-SA': 'ar_SA' };

/** Public helper: og:locale for a given app locale (falls back to the raw locale). */
export const ogLocale = (locale: string) => OG_LOCALE[locale] ?? locale;

/**
 * Per-page, per-locale share card (1200x630 JPEG, <600 KB for WhatsApp), generated by
 * scripts/brand/og.py into public/og/<locale>/<slug>.jpg. Relative URL; metadataBase
 * in the layout makes it absolute, which WhatsApp/LinkedIn require.
 */
// Bump when the cards are re-rendered (og.py --all): Cloudflare and social networks cache images for months.
const OG_VERSION = '20261007';
export function ogImage(locale: string, route: string, alt: string) {
  const slug = route === '/' || route === '' ? 'home' : route.replace(/^\//, '').replace(/\//g, '-');
  return { url: `/og/${locale}/${slug}.jpg?v=${OG_VERSION}`, width: 1200, height: 630, type: 'image/jpeg', alt };
}

/** { en: "/en{path}", ar: "/ar{path}", "x-default": "/en{path}" } — for alternates.languages. */
export function hreflangLanguages(path: string): Record<string, string> {
  const languages: Record<string, string> = {};
  for (const l of routing.locales) languages[l] = `/${l}${path}`;
  languages['x-default'] = `/${routing.defaultLocale}${path}`;
  return languages;
}

/** Absolute per-route URLs across every locale — used by the sitemap. */
export function absoluteLanguages(path: string): Record<string, string> {
  return Object.fromEntries(routing.locales.map((l) => [l, `${SITE_URL}/${l}${path}`]));
}

/**
 * Factory: returns a `generateMetadata` for a page. Reads localized
 * title/description from the `seo.<seoKey>` message block and emits a
 * self-referencing canonical + per-locale hreflang + x-default + OG/Twitter.
 */
export function pageMetadata({ route, seoKey }: { route: string; seoKey: string }) {
  const path = route === '/' ? '' : route;
  return async function generateMetadata({
    params
  }: {
    params: Promise<{ locale: string }>;
  }): Promise<Metadata> {
    const { locale } = await params;
    const t = await getTranslations({ locale, namespace: 'seo' });
    const title = t(`${seoKey}.title`);
    const description = t(`${seoKey}.description`);
    const url = `/${locale}${path}`;
    const image = ogImage(locale, route, title);
    return {
      title,
      description,
      alternates: { canonical: url, languages: hreflangLanguages(path) },
      openGraph: {
        type: 'website',
        url,
        siteName: 'GenuDo',
        title,
        description,
        locale: OG_LOCALE[locale] ?? locale,
        alternateLocale: routing.locales.filter((l) => l !== locale).map((l) => OG_LOCALE[l] ?? l),
        images: [image]
      },
      twitter: { card: 'summary_large_image', title, description, images: [image] }
    };
  };
}

// --- Organization / brand facts (single source of truth for JSON-LD) --------
/**
 * Canonical entity statement (docs/seo/GEO-STRATEGY.md section 1). Use the same
 * wording on every profile (LinkedIn, G2, Crunchbase, YouTube): AI engines build
 * the brand entity from repeated, consistent descriptions.
 */
export const ENTITY = {
  en: 'GenuDo is an AI workforce platform for businesses in Egypt and the Middle East. It gives you AI employees (Aaref, the AI sales employee; Adnan, the AI customer service and success employee; and Roz, the AI quality control employee). Aaref and Adnan answer customers on WhatsApp, Instagram, Messenger and website chat in Arabic dialects and other languages, follow up and keep your records current. Roz is linked to your company WhatsApp with one QR scan and answers your questions about your team’s chats through Claude or ChatGPT. Your team stays in control.',
  ar: 'جينـو دو منصة فريق عمل بالذكاء الاصطناعي للشركات في مصر والشرق الأوسط. بتديك موظفين بالذكاء الاصطناعي: عارف موظف المبيعات، وعدنان موظف خدمة ونجاح العملاء، وروز موظفة مراقبة الجودة. عارف وعدنان بيردوا على عملائك على WhatsApp و Instagram و Messenger وشات الموقع بلهجتهم، ويتابعوا ويحدّثوا الـ CRM. وروز بتتربط بـ WhatsApp الشركة بمسح كود QR واحد وبتجاوب على أسئلتك عن محادثات فريقك من Claude أو ChatGPT. وإنت متحكم في كل حاجة.'
};

export const ORG = {
  name: 'GenuDo',
  legalName: 'GenuDo',
  alternateName: ['Genudo', 'جينـو دو', 'جينو دو'],
  url: SITE_URL,
  logo: `${SITE_URL}/icon-512.png`, // square mark: what Google shows for the brand
  email: 'info@genudo.ai',
  knowsAbout: [
    'AI workforce',
    'AI employees',
    'AI agents for business',
    'AI sales employee',
    'AI customer service and success',
    'WhatsApp AI employee',
    'WhatsApp quality control',
    'Conversational AI in Arabic',
    'موظفين بالذكاء الاصطناعي',
    'خدمة عملاء بالذكاء الاصطناعي'
  ],
  sameAs: [
    'https://www.facebook.com/genudo.official/',
    'https://www.linkedin.com/company/genudo/',
    'https://www.youtube.com/@GenuDoAi',
    'https://www.tiktok.com/@genudo.official'
  ]
};

/** JSON-LD graph (Organization + WebSite) for GEO / rich results. Injected in the root layout. */
export function siteJsonLd(locale: string) {
  const description = locale.startsWith('ar') ? ENTITY.ar : ENTITY.en;
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': `${SITE_URL}/#organization`,
        name: ORG.name,
        legalName: ORG.legalName,
        alternateName: ORG.alternateName,
        url: ORG.url,
        logo: { '@type': 'ImageObject', url: ORG.logo, width: 512, height: 512 },
        email: ORG.email,
        description,
        knowsAbout: ORG.knowsAbout,
        areaServed: [{ '@type': 'Place', name: 'Middle East and North Africa' }],
        contactPoint: { '@type': 'ContactPoint', contactType: 'sales', email: ORG.email, availableLanguage: ['Arabic', 'English'] },
        sameAs: ORG.sameAs
      },
      {
        '@type': 'WebSite',
        '@id': `${SITE_URL}/#website`,
        url: `${SITE_URL}/${locale}`,
        name: ORG.name,
        alternateName: ORG.alternateName,
        description,
        inLanguage: locale,
        publisher: { '@id': `${SITE_URL}/#organization` }
      }
    ]
  };
}
