import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getTranslations, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { Tajawal } from 'next/font/google';
import { routing, isRtl } from '@/i18n/routing';
import { SITE_URL, hreflangLanguages, siteJsonLd, ogLocale, ogImage } from '@/i18n/seo';
import SiteNav from '@/components/SiteNav';
import SiteFooter from '@/components/SiteFooter';

// --- Global styles: the ORIGINAL stylesheets, reused verbatim. -------------
// Import order mirrors the legacy <head> so the cascade is identical.
import '@/styles/genudo-site.css';
import '@/styles/site2.css';
import '@/styles/genu-robot.css';
import '@/styles/concept.css';
import '@/styles/home.css';
import '@/styles/hero.css';
import '@/styles/features.css';
import '@/styles/pages.css';
import '@/styles/resources.css';
import '@/styles/chrome.css'; // nav + footer styles (ported from site-chrome.js)
import '@/styles/mockups.css'; // shared product-UI mockup kit (EN + AR)
import '@/styles/layout-rules.css'; // 3/6 card grids, one-line hero chips (all breakpoints)
import '@/styles/rtl.css'; // scoped to [dir=rtl] / [lang=ar] — leaves EN untouched

// Arabic UI font (Egypt + Gulf). Latin copy keeps the stack from genudo-site.css.
const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['400', '500', '700', '800'],
  variable: '--font-ar',
  display: 'swap'
});

export async function generateMetadata({
  params
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'seo' });
  const title = t('default.title');
  const description = t('default.description');
  return {
    metadataBase: new URL(SITE_URL),
    title: { default: title, template: '%s · GenuDo' },
    description,
    applicationName: 'GenuDo',
    alternates: { canonical: `/${locale}`, languages: hreflangLanguages('') },
    openGraph: {
      type: 'website',
      siteName: 'GenuDo',
      title,
      description,
      url: `/${locale}`,
      locale: ogLocale(locale),
      images: [ogImage(locale, '/', title)]
    },
    twitter: { card: 'summary_large_image', title, description, images: [ogImage(locale, '/', title)] },
    robots: { index: true, follow: true },
    // Generated by scripts/brand/icons.py from the "do" mark.
    icons: {
      icon: [
        { url: '/favicon.ico', sizes: '48x48' },
        { url: '/icon.svg', type: 'image/svg+xml' }
      ],
      apple: { url: '/apple-touch-icon.png', sizes: '180x180' }
    },
    manifest: '/site.webmanifest'
  };
}

export const viewport: Viewport = {
  themeColor: '#ffffff'
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as never)) notFound();

  // Enables static rendering for this locale.
  setRequestLocale(locale);

  const messages = await getMessages();
  const t = await getTranslations({ locale, namespace: 'seo' });
  const rtl = isRtl(locale);
  const dir = rtl ? 'rtl' : 'ltr';

  return (
    <html lang={locale} dir={dir} className={rtl ? tajawal.variable : undefined}>
      <body className={rtl ? 'is-ar' : undefined}>
        {/* GEO / rich results: Organization + WebSite graph (own trusted data). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteJsonLd(locale, t('default.description'))) }}
        />
        <NextIntlClientProvider messages={messages}>
          <SiteNav />
          {children}
          <SiteFooter />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
